apiVersion: app/v1
kind: Deployment
metadata: 
    name: {{ .Values.name.frontend }}
    labels:
        {{- include "backend-labels" . }}
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchlabels:
            {{- include "backend-labels" . | indent 2 }}
    template:
        metadata:
            labels:
                {{- include "backend-labels" . | indent 4 }}
        spec:
            containers:
                - name: utopia-frontend
                  image: {{ .Values.image.frontend-repository }}:{{ .Values.image.tag }}
                  ports:
                    - name: http
                      containerPort: 80
                      protocol: TCP